### ISSUE TITLE
Replace server API URL with official one

### ISSUE THREAD

**Issue by tomas-polach** [archilogic-com/aframe-gblock#1]
To get the official glTF URL of a google blocks model currently a server instance is required. I am providing one at `https://gblock.herokuapp.com/get-gltf-url/<google-blocks-url>`

TODO:
- replace custom API with official one once available.

https://github.com/archilogic-com/aframe-gblock/blob/master/src/gblock.js#L10

**Comment by deprecatedcoder** [comment]
Wish granted!

https://developers.google.com/poly/

**Comment by antoniohof** [comment]
I made a pull request to use official api url #7

**Comment by tomas-polach** [comment]
thx @antoniohof !
