### ISSUE TITLE
Breaks in A-Frame 7.0

### ISSUE THREAD

**Issue by gabrieljbaker** [archilogic-com/aframe-gblock#2]
Looks like this component doesn't work in A-Frame 7.0 because of the new .gltf loader!

**Comment by tomas-polach** [comment]
Thanks for letting me know. I added A-Frame 7 support in https://github.com/archilogic-com/aframe-gblock/commit/2d2b09b3c944029519377b3454a06d7a99168f66 

Pls let me know if you still encounter issues. I'm happy to fix it.
