### ISSUE TITLE
Update to work with poly

### ISSUE THREAD

**Issue by urish** [archilogic-com/aframe-gblock#3]
Seems like gblock has been rebranded as poly: https://poly.google.com

I tried to use this component with modules from poly, but it seems to be broken. For instance:

    <a-entity gblock="https://vr.google.com/objects/2tAgPX9As4I"></a-entity>

fails with an 404 error, even though the model exists (the above URL redirects to the new poly URL: https://poly.google.com/view/2tAgPX9As4I).

**Comment by deprecatedcoder** [comment]
It seems to me like this might just be a matter of changing [line 118](https://github.com/archilogic-com/aframe-gblock/blob/master/server/api-methods.js#L118) and the following line in api-methods.js to point to http://poly.google.com/view, but I can't test it at the moment.  If someone doesn't get to it before then, I will try and make the change, test and create a pull request.

**Comment by AVGP** [comment]
I think @tomas-polach is working on this

**Comment by triptych** [comment]
This breaks the demo as well - no tie fighters, no AT AT's :(

**Comment by tomas-polach** [comment]
fixed breaking vr.google.com legacy domains in:
- 1b11588a98b4248a205cd41dc3a57301c6e5856f
- 40b353e2bb97048f06432be0788db3dc04b75ad7

added support for poly.google.com in:
- 40b353e2bb97048f06432be0788db3dc04b75ad7

@urish @triptych thx for making me aware of this!
@deprecatedcoder thx! you were right: updating line 118 was key
