### ISSUE TITLE
Download URL does not always default to the same format

### ISSUE THREAD

**Issue by deprecatedcoder** [archilogic-com/aframe-gblock#4]
Hey there @tomas-polach, thanks for the update to use the models from Poly.  I discovered a problem with it while poking around though, so I thought I would let you know about it.

Using your [codepen example](https://codepen.io/tomas-polach/pen/NvJRJe?editors=1000), if I replace the gblock with [this Pillow](https://poly.google.com/view/f60emm1Xkas) then it does not work.

I noticed that if I go to the download option on the page it returns a zipped OBJ file, but when going to the [download URL you construct](https://poly.google.com/downloads/f60emm1Xkas) then it returns a glTF.

The model you used as an example yields an unzipped OBJ when getting it's [download URL](https://poly.google.com/downloads/dVG0XJrpRJC).

I tested this with a few others and the ones that are an OBJ load fine, while the ones that are a glTF do not.

I don't really know enough about the different formats to give any more thoughts on how to fix it, but figured the diagnosis might help.  Thanks again for your work on this component.  It really is super useful.

**Comment by deprecatedcoder** [comment]
Looked at this a little more tonight and it seems to stem from models where the model name is not explicitly "model", like the previous Pillow example which uses "pillow".  It seemed to me like this might be a problem with the gblock update method, but I'm not familiar enough for it to be immediately apparent.

This [Space Shuttle](https://poly.google.com/view/djxolbz_CYC), which uses "SpaceShuttle(1)", even fails to load completely and throws the "Model not found" error, but that is because it has parens and [this regex](https://github.com/archilogic-com/aframe-gblock/blob/master/server/api-methods.js#L153) doesn't handle it.

**Comment by tomas-polach** [comment]
good catch! will fix.

thx for all the details. it helps with debugging

**Comment by tomas-polach** [comment]
i fixed the regex issue but some poly models were still not loading: turns out they are GLTF v2. 

created new issue: #5

**Comment by tomas-polach** [comment]
@deprecatedcoder can you pls confirm if the updated code is working for you as expected? in combination with the resolved #5 space shuttle is loading for me :)

**Comment by deprecatedcoder** [comment]
Just threw everything I could at it and it loads them all now.  Fix looks good.  Thanks!

**Comment by tomas-polach** [comment]
thanks for testing! looking at the new issue now... :D
