### ISSUE TITLE
using gblock in multiple domains simultaneously on Chrome results in CORS issues

### ISSUE THREAD

**Issue by deprecatedcoder** [archilogic-com/aframe-gblock#6]
I swear I am not trying to break things :-D

When putting together a [simple AR viewer](https://glitch.com/edit/#!/poly-view?path=index.html) for Poly models I ran into the following error when trying to use [this model](https://poly.google.com/view/3ZSb03wXp0w):

> Failed to load https://poly.google.com/downloads/3ZSb03wXp0w/5xjsVY0DLe8/tinker.bin: The 'Access-Control-Allow-Origin' header has a value 'https://s.codepen.io' that is not equal to the supplied origin. Origin 'https://poly-view.glitch.me' is therefore not allowed access.

It worked for various other ones I tried (as commented out there), so I am not sure if it's just this specific model or not.  I suspect it might be with caching on your pseudo-API server?  I am pretty sure I tried to pull in that model from the codepen example first, otherwise I don't really have any idea.

**Comment by tomas-polach** [comment]
i was able to reproduce it:

this happens when in the rare case of loading poly model in two tabs from two different domains. (in your case: codepen and glitch.me). i was only able to reproduce it in chrome. it's a CORS issue in the request going from chrome to poly.gogle.com (the pseudo-API server is not involved.) It looks like a bug in CORS implementation either on browser or server side. reloading with cache disabled resolves it. not sure what i could do about this...

i guess it will not affect users because they are mostly not loading poly models from various domains.

and hell yes: keep on breaking things! ;D

**Comment by deprecatedcoder** [comment]
Ah, that makes a lot of sense and yeah, doesn't sound like it would be worth pursuing any kind of fix.  It was an odd situation to be trying out anyway.  Thanks for looking into it.  I'll keep pulling threads 👍

**Comment by banada** [comment]
This happens for me as well, but with only one domain.
You can use my site to test, it works in Firefox but not Chrome:

https://banada.github.io/aframe-object-scaling/

Thanks!

**Comment by tomas-polach** [comment]
@banada i get a 404 when following the link. Have you been able to resolve the issue in meanwhile? (would love to know how you fixed it)

**Comment by banada** [comment]
@tomas-polach sorry the link has moved to https://banada.github.io/webvr/aframe-object-scaling

**Comment by tomas-polach** [comment]
@banada Your example works really well! I actually too well: I can't reproduce the error :D 

Idea: try using the lib with a Poly API Key:
``` html
// 1. replace
<script src="https://dist.3d.io/3dio-js/1.x.x/3dio.min.js"></script>
// with
<script src="https://cdn.rawgit.com/archilogic-com/aframe-gblock/6498b71d/dist/gblock.js"></script>

// 2. replace
<a-entity id="model" gblock="https://poly.google.com/view/bf6_h_1wp2D"></a-entity>
// with
<a-entity id="model" gblock="https://poly.google.com/view/bf6_h_1wp2D?key=YOUR_POLY_API_KEYHERE"></a-entity>
```

I will update the docs accordingly. Using the Poly AKI Key is the recommended way and might also help with CORS issues. Pls let me know if it helps.

**Comment by banada** [comment]
@tomas-polach Works just fine now, even without changing anything. CORS issues are the worst >.< Thanks for the help!

**Comment by tomas-polach** [comment]
@banada I'm really glad to hear that! yeah, CORS ... >.<
